version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql_container
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: gestion_empleados
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_USER: user
            MYSQL_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - ./db_data:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
